### ISSUE TITLE
THANK YOU!

### ISSUE THREAD

**Issue by linda535** [ambiren/FishingMode#2]
I've been hoping for literally YEARS to get an addon to use the kb for fishing - carpal tunnel... I've found a workaround for the HUGE overlay by turning my character's camera - NOT the character's direction -  away from the bobber so I can see it. Thanks so much!!!

**Comment by ambiren** [comment]
That's wonderful to hear! This addon started as something I was just making for myself. So now knowing that it's a helpful accessibility tool makes me glad I decided to take the time to polish up and publish the addon for anyone to use.

I hope that my recent changes to let you move or disable the overlay have improved your experience even more.
